### ISSUE TITLE
Add download option

### ISSUE THREAD

**Issue by NorthForce9** [Based-Programmer/wco-cli#1]
hello ,
can please add option that do download from link to anime episode like -a wcostream.net/cartoon/1234 so it can be complete

thx u

**Comment by Based-Programmer** [comment]
unfortunately its currently out of scope of this project
i actually wrote this script abt a yr & i don't even use it anymore
i do hv a rust rewrite which is much faster
tho i hvn't uploaded it to git yet

**Comment by NorthForce9** [comment]
i try to understand the code and modify it because to be honest i am otako and i really like it but i couldn't understand it i try to make my version in golang but i hit 403 wall and i couldn't extract the mp4 link so how did u bypass that i don't want to use selenium bwcuse it will make it slower 

but i would love to see rust script you made

**Comment by Based-Programmer** [comment]
> i try to understand the code and modify it because to be honest i am otako and i really like it but i couldn't understand it i try to make my version in golang but i hit 403 wall and i couldn't extract the mp4 link so how did u bypass that i don't want to use selenium bwcuse it will make it slower
> 
> but i would love to see rust script you made

403 ?
maybe bcz of cloudflare or ur doing get request instead of post

**Comment by Based-Programmer** [comment]
i just added -a feature as u requested
see if it wrks for u
i havn't tested much tho

**Comment by Based-Programmer** [comment]
> i try to understand the code and modify it because to be honest i am otako and i really like it but i couldn't understand it i try to make my version in golang but i hit 403 wall and i couldn't extract the mp4 link so how did u bypass that i don't want to use selenium bwcuse it will make it slower
> 
> but i would love to see rust script you made

fixed issue
